#!/bin/bash

# ==============================================================================
# TITRE : Setup post install de Debian 13
# DESCRIPTION : Mises à jour, BinUtils, Samba/Netbios, Bashrc, Webmin, MiniJeux
# ==============================================================================

# ==============================================================================
# 1. MISE À JOUR
# ==============================================================================

echo "Mise à Jour du système en cours..."
apt update && apt upgrade -y

# ==============================================================================
# 2. INSTALLATIONS DES PAQUETS
# ==============================================================================

echo "Installation des BinUtils..."
apt install ssh zip nmap locate ncdu curl git screen dnsutils net-tools sudo lynx -y

echo "Installation des paquets Samba/Netbios..."
apt install winbind samba -y

echo "Installation des BSDGAMES..."
apt install bsdgames -y

# ==============================================================================
# 3. CONFIGURATION SYSTÈME & FICHIERS
# ==============================================================================

echo "Mise à jour de l'index locate..."
updatedb

echo"Création de nsswitch.conf.bak"
cp /etc/nsswitch.conf /etc/nsswitch.conf.bak

echo "Ajout de WINS dans nsswitch.conf..."
cat << REMPLACER > /etc/nsswitch.conf
passwd:         files systemd winbind
group:          files systemd winbind
shadow:         files systemd
gshadow:        files systemd

hosts:          files dns wins
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
REMPLACER

echo "Activation des options dans le .bashrc..."
cat << AJOUT >> /root/.bashrc
export LS_OPTIONS='--color=auto'
eval "\$(dircolors)"
alias ls='ls \$LS_OPTIONS'
alias ll='ls \$LS_OPTIONS -l'
alias l='ls \$LS_OPTIONS -lA'
AJOUT

# ==============================================================================
# 4. INSTALLATION WEBMIN
# ==============================================================================

echo "Installation de Webmin..."

curl -o webmin-setup-repo.sh https://raw.githubusercontent.com/webmin/webmin/master/webmin-setup-repo.sh

sh webmin-setup-repo.sh --force

apt install webmin -y --install-recommends

rm webmin-setup-repo.sh

# ==============================================================================
# 5. SUPPRESSION .SH
# ==============================================================================

rm debian_post_install

echo "=========================================================================="
echo "L'installation est Finie !"
echo "=========================================================================="
echo "Infos :"
echo "   - Ton IP actuelle (DHCP) est :"
hostname -I
echo "   - Webmin accessible via : https://TON_IP:10000"
echo "   - Jeux disponibles dans /usr/games"
